export const TABLE_NAMES = {
  users: 'users',
  sessions: 'sessions',
  accounts: 'accounts',
  verifications: 'verifications',
  facilities: 'facilities',
  projects: 'projects',
  maps: 'maps',
  mapKeys: 'map_keys',
  mapMarkers: 'map_markers',
  markerPhotos: 'marker_photos',
  twoFactors: 'two_factors',
  passkeyCredentials: 'passkey_credentials',
  pushDevices: 'push_devices',
  userFacilities: 'user_facilities',
  teammates: 'teammates',
} as const;

export const COLUMNS = {
  users: {
    id: 'id',
    email: 'email',
    name: 'name',
    firstName: 'first_name',
    lastName: 'last_name',
    role: 'role',
    emailVerified: 'email_verified',
    image: 'image',
    isActive: 'is_active',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  sessions: {
    id: 'id',
    userId: 'user_id',
    token: 'token',
    expiresAt: 'expires_at',
    ipAddress: 'ip_address',
    userAgent: 'user_agent',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  accounts: {
    id: 'id',
    userId: 'user_id',
    accountId: 'account_id',
    providerId: 'provider_id',
    accessToken: 'access_token',
    refreshToken: 'refresh_token',
    accessTokenExpiresAt: 'access_token_expires_at',
    refreshTokenExpiresAt: 'refresh_token_expires_at',
    scope: 'scope',
    idToken: 'id_token',
    password: 'password',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  verifications: {
    id: 'id',
    identifier: 'identifier',
    value: 'value',
    expiresAt: 'expires_at',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  facilities: {
    id: 'id',
    name: 'name',
    address: 'address',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  projects: {
    id: 'id',
    name: 'name',
    description: 'description',
    address: 'address',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  maps: {
    id: 'id',
    projectId: 'project_id',
    facilityId: 'facility_id',
    name: 'name',
    description: 'description',
    fileType: 'file_type',
    fileUri: 'file_uri',
    fileName: 'file_name',
    fileSize: 'file_size',
    width: 'width',
    height: 'height',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  mapKeys: {
    id: 'id',
    mapId: 'map_id',
    label: 'label',
    iconName: 'icon_name',
    iconColor: 'icon_color',
    iconShape: 'icon_shape',
    customIconUri: 'custom_icon_uri',
    sortOrder: 'sort_order',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  mapMarkers: {
    id: 'id',
    mapId: 'map_id',
    keyId: 'key_id',
    x: 'x',
    y: 'y',
    label: 'label',
    description: 'description',
    status: 'status',
    createdBy: 'created_by',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  markerPhotos: {
    id: 'id',
    markerId: 'marker_id',
    fileUri: 'file_uri',
    fileName: 'file_name',
    fileSize: 'file_size',
    caption: 'caption',
    takenAt: 'taken_at',
    createdAt: 'created_at',
  },
  twoFactors: {
    id: 'id',
    userId: 'user_id',
    secret: 'secret',
    backupCodes: 'backup_codes',
    enabled: 'enabled',
  },
  passkeyCredentials: {
    id: 'id',
    userId: 'user_id',
    credentialId: 'credential_id',
    publicKey: 'public_key',
    counter: 'counter',
    deviceType: 'device_type',
    backedUp: 'backed_up',
    transports: 'transports',
    deviceName: 'device_name',
    isActive: 'is_active',
    lastUsedAt: 'last_used_at',
    createdAt: 'created_at',
  },
  pushDevices: {
    id: 'id',
    userId: 'user_id',
    platform: 'platform',
    token: 'token',
    environment: 'environment',
    isActive: 'is_active',
    lastSeenAt: 'last_seen_at',
    deviceId: 'device_id',
    deviceModel: 'device_model',
    appVersion: 'app_version',
    buildNumber: 'build_number',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
  userFacilities: {
    id: 'id',
    userId: 'user_id',
    facilityId: 'facility_id',
    createdAt: 'created_at',
  },
  teammates: {
    id: 'id',
    userId: 'user_id',
    teammateId: 'teammate_id',
    role: 'role',
    createdAt: 'created_at',
    updatedAt: 'updated_at',
  },
} as const;
